### CREATE AN ACCOUNT
POST http://localhost:8080/api/user/createAccount
Content-Type: application/json

{
  "username": "titi",
  "email": "titi@titi.fr",
  "password": "123456"
}

### ACTIVATE AN ACCOUNT
POST http://localhost:8080/api/user/activateAccount
Content-Type: application/json

{
  "activationKey": "884612"
}

### REQUEST A NEW ACTIVATION KEY
POST http://localhost:8080/api/user/requestNewActivationKey?username=elie

### REMOVE NOT ACTIVATED ACCOUNTS (ONLY FOR TEST)
POST http://localhost:8080/api/user/removeNotActivatedAccounts

### AUTHENTICATE AS CUSTOMER
POST http://localhost:8080/api/user/authenticate
Content-Type: application/json

{
  "username": "titi",
  "password": "newPassword123"
}

### AUTHENTICATE AS ADMIN
POST http://localhost:8080/api/user/authenticate
Content-Type: application/json

{
  "username": "admin",
  "password": "admin@pass123"
}

### AUTHENTICATE AS EDITOR
POST http://localhost:8080/api/user/authenticate
Content-Type: application/json

{
  "username": "editor",
  "password": "editor@pass123"
}

### FIND ALL USERS AS CUSTOMER
GET http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6Impvam8iLCJzdWIiOiJqb2pvIiwiZXhwIjoxNzE4MzYzMDY2LCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9XSwiaWF0IjoxNzE4MzYxMjY2fQ.hKDFIy3UYBXUlRvomENITe0XlgDjipfADVXXnL3MtUcmDBaN0YkdijsczP503tfBGbOXNkHmSlVYgdzdE-6BIA

### FIND ALL USERS AS ADMIN
GET http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3MTg3MDcyNzIsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJST0xFX0VESVRPUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9XSwiaWF0IjoxNzE4NzA1NDcyLCJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiYWRtaW4ifQ.492NTkYsN0kEbXFzdRZyvV9Cp4rnTD9vlBoDFgDb-dsyzgSdfG6bowcGgcVLEWul_f0SgjC3GMDlGX-kabESbw

### FIND ALL USERS AS EDITOR
GET http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6ImVkaXRvciIsInN1YiI6ImVkaXRvciIsImV4cCI6MTcxODM2MzU2OCwiYXV0aG9yaXRpZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfRURJVE9SIn0seyJhdXRob3JpdHkiOiJST0xFX0NVU1RPTUVSIn1dLCJpYXQiOjE3MTgzNjE3Njh9.BZwymyJTwZwIDgMMMXwrPmLXuMtBtk3DtUoEMGXYMsqyLS2wRZQh0MEm_8LSL6c34_oSI3_3B_QhBScDG3gAkw

### FORGOT PASSWORD
POST http://localhost:8080/api/user/forgotPassword?email=jean@jean.fr

### RESET PASSWORD
POST http://localhost:8080/api/user/resetPassword?key=2ab28d74-60db-430a-ba3b-dcebfe507cac
Content-Type: application/json

{
  "newPassword": "newPassword123",
  "confirmPassword": "newPassword123"
}

### UPDATE PASSWORD (USER CONNECTED)
PUT http://localhost:8080/api/user/updatePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTg3MDc5NjUsInVzZXJuYW1lIjoiZWRpdG9yIiwic3ViIjoiZWRpdG9yIiwiZXhwIjoxNzE4NzA5NzY1LCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9FRElUT1IifSx7ImF1dGhvcml0eSI6IlJPTEVfQ1VTVE9NRVIifV19.Jxpd6rCMs1PysMBZUHqL5dkBLVGT3NwY43nECksTcooeLi2ZxyeJyBwBw1Kj8ICrTV-TN8nGYNePVHEw40KfYg

{
  "currentPassword": "editor@pass123",
  "newPassword": "newPassword123v2"
}

###