### USER API POST
### CREATE AN ACCOUNT
POST http://localhost:8080/api/user/createAccount
Content-Type: application/json

{
  "username": "paul",
  "email": "paul@example.fr",
  "password": "123456"
}