@startuml shopclassdiagram

User "*" -right- "*" Authority

abstract class Audit {
    - createdBy: String
    - createdDate: Instant
    - lastModifiedBy: String
    - lastModifiedDate: Instant
}

interface UserDetails {
    + getAuthorities(): Collection <? extends GrantedAuthority>
    + getPassword(): String
    + getUsername(): String
    + isAccountNonExpired(): boolean
    + isAccountNonLocked(): boolean
    + isCredentialsNonExpired(): boolean
    + isEnabled(): boolean
}

class User extends Audit
class User implements UserDetails
class User {
    - userId: Long
    - password: String
    - username: String  
    - email: String
    - activated: boolean
    - authorities: Set<Authority>

    - activationKey: String
    - activationKeyExpiration: Instant

    - passwordResetKey: String
    - passwordResetKeyExpiration: Instant

    + createAccount(UserDTO userDTO): void
    + activateAccount(Map<String, String> activation): void
    + requestNewActivationKey(String username): void
    + removeNotActivatedAccounts(): void

    + loadUserByUsername(String username): User
    + authenticate(UserAuthenticationDTO userAuthenticationDTO): Map<String, String>
    + doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain): void

    + forgotPassword(String email): void
    + resetPassword(String passwordResetKey, UserPasswordResetDTO userPasswordResetDTO): void
    + updatePassword(UserPasswordUpdateDTO userPasswordUpdateDTO): void
    + updateUserDetails(UserDetailsUpdateDTO userDetailsUpdateDTO): void

    + findAll(): List<UserDTO>
}

class Authority {
    - authorityLabel: String
}

@enduml